### ISSUE TITLE
FileNotFound Exception after the recent playground update

### ISSUE THREAD

**Issue by mananwason** [CrimsonVista/Playground3#3]
Getting this error after the latest update. IT says some connector file doesn't belong. Here is the stacktrace.

```
Traceback (most recent call last):
  File "/home/manan/Assignment1b/netsec_fall2017/lab_1e/submission.py", line 59, in <module>
    coro = playground.getConnector("PT1").create_playground_server(lambda: MoviesServer(), 101)
  File "/home/manan/Assignment1b/lib/python3.5/site-packages/playground/network/devices/vnic/connect.py", line 352, in getConnector
    self.reloadConnectors()
  File "/home/manan/Assignment1b/lib/python3.5/site-packages/playground/network/devices/vnic/connect.py", line 348, in reloadConnectors
    for pathName in os.listdir(connectorLocation):
FileNotFoundError: [Errno 2] No such file or directory: '/home/manan/.playground/connectors'
```

**Comment by jbschahal** [comment]
Same error.

**Comment by jbschahal** [comment]
Create a folder "connectors" in .playground and the issue is resolved.

**Comment by mananwason** [comment]
Yes I figured that out after the piazza post.
